name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setting up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Run tests
      - name: Run tests
        run: |
          python -m pytest  # Add your test command here

      # Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Building and pushing the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t kal5257/ci-cd_pipeline:latest .
          docker push kal5257/ci-cd_pipeline:latest


      # Heroku deployment
      - name: Deploy to Heroku
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/flask-devops-app:latest registry.heroku.com/glacial-lowlands-50508/web
          docker push registry.heroku.com/glacial-lowlands-50508/web
          heroku container:release web -a glacial-lowlands-50508